/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BantuanRouteImport } from './routes/bantuan'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as PrivasiRouteImport } from './routes/privasi'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminIklanRouteImport } from './routes/_authenticated/admin.iklan'
import { Route as AuthenticatedAdminInfoRouteImport } from './routes/_authenticated/admin.info'
import { Route as AuthenticatedAdminQrRouteImport } from './routes/_authenticated/admin.qr'
import { Route as AuthenticatedAdminRegionRouteImport } from './routes/_authenticated/admin.region'
import { Route as RSlugLocRouteImport } from './routes/r.$slug_.$loc'
import { Route as RSlugJelajahRouteImport } from './routes/r.$slug_.jelajah'
import { Route as RSlugMessagesRouteImport } from './routes/r.$slug_.messages'
import { Route as RSlugScanRouteImport } from './routes/r.$slug_.scan'
import { Route as RSlugSettingsRouteImport } from './routes/r.$slug_.settings'
import { Route as RSlugKategoriIndexRouteImport } from './routes/r.$slug_.kategori.index'
import { Route as RSlugKategoriCatRouteImport } from './routes/r.$slug_.kategori.$cat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BantuanRoute = BantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivasiRoute = PrivasiRouteImport.update({
  id: '/privasi',
  path: '/privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIklanRoute = AuthenticatedAdminIklanRouteImport.update({
  id: '/iklan',
  path: '/iklan',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInfoRoute = AuthenticatedAdminInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQrRoute = AuthenticatedAdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRegionRoute =
  AuthenticatedAdminRegionRouteImport.update({
    id: '/region',
    path: '/region',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const RSlugLocRoute = RSlugLocRouteImport.update({
  id: '/r/$slug_/$loc',
  path: '/r/$slug/$loc',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugJelajahRoute = RSlugJelajahRouteImport.update({
  id: '/r/$slug_/jelajah',
  path: '/r/$slug/jelajah',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugMessagesRoute = RSlugMessagesRouteImport.update({
  id: '/r/$slug_/messages',
  path: '/r/$slug/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugScanRoute = RSlugScanRouteImport.update({
  id: '/r/$slug_/scan',
  path: '/r/$slug/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugSettingsRoute = RSlugSettingsRouteImport.update({
  id: '/r/$slug_/settings',
  path: '/r/$slug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugKategoriIndexRoute = RSlugKategoriIndexRouteImport.update({
  id: '/r/$slug_/kategori/',
  path: '/r/$slug/kategori/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugKategoriCatRoute = RSlugKategoriCatRouteImport.update({
  id: '/r/$slug_/kategori/$cat',
  path: '/r/$slug/kategori/$cat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bantuan': typeof BantuanRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/notifikasi': typeof NotifikasiRoute
  '/privasi': typeof PrivasiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/q/$code': typeof QCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/iklan': typeof AuthenticatedAdminIklanRoute
  '/admin/info': typeof AuthenticatedAdminInfoRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/region': typeof AuthenticatedAdminRegionRoute
  '/r/$slug/$loc': typeof RSlugLocRoute
  '/r/$slug/jelajah': typeof RSlugJelajahRoute
  '/r/$slug/messages': typeof RSlugMessagesRoute
  '/r/$slug/scan': typeof RSlugScanRoute
  '/r/$slug/settings': typeof RSlugSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/r/$slug/kategori/$cat': typeof RSlugKategoriCatRoute
  '/r/$slug/kategori/': typeof RSlugKategoriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bantuan': typeof BantuanRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/notifikasi': typeof NotifikasiRoute
  '/privasi': typeof PrivasiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/q/$code': typeof QCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/iklan': typeof AuthenticatedAdminIklanRoute
  '/admin/info': typeof AuthenticatedAdminInfoRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/region': typeof AuthenticatedAdminRegionRoute
  '/r/$slug/$loc': typeof RSlugLocRoute
  '/r/$slug/jelajah': typeof RSlugJelajahRoute
  '/r/$slug/messages': typeof RSlugMessagesRoute
  '/r/$slug/scan': typeof RSlugScanRoute
  '/r/$slug/settings': typeof RSlugSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/r/$slug/kategori/$cat': typeof RSlugKategoriCatRoute
  '/r/$slug/kategori': typeof RSlugKategoriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bantuan': typeof BantuanRoute
  '/explore': typeof ExploreRoute
  '/messages': typeof MessagesRoute
  '/notifikasi': typeof NotifikasiRoute
  '/privasi': typeof PrivasiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/q/$code': typeof QCodeRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/iklan': typeof AuthenticatedAdminIklanRoute
  '/_authenticated/admin/info': typeof AuthenticatedAdminInfoRoute
  '/_authenticated/admin/qr': typeof AuthenticatedAdminQrRoute
  '/_authenticated/admin/region': typeof AuthenticatedAdminRegionRoute
  '/r/$slug_/$loc': typeof RSlugLocRoute
  '/r/$slug_/jelajah': typeof RSlugJelajahRoute
  '/r/$slug_/messages': typeof RSlugMessagesRoute
  '/r/$slug_/scan': typeof RSlugScanRoute
  '/r/$slug_/settings': typeof RSlugSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/r/$slug_/kategori/$cat': typeof RSlugKategoriCatRoute
  '/r/$slug_/kategori/': typeof RSlugKategoriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bantuan'
    | '/explore'
    | '/messages'
    | '/notifikasi'
    | '/privasi'
    | '/reset-password'
    | '/saved'
    | '/scan'
    | '/settings'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin'
    | '/q/$code'
    | '/r/$slug'
    | '/admin/analytics'
    | '/admin/iklan'
    | '/admin/info'
    | '/admin/qr'
    | '/admin/region'
    | '/r/$slug/$loc'
    | '/r/$slug/jelajah'
    | '/r/$slug/messages'
    | '/r/$slug/scan'
    | '/r/$slug/settings'
    | '/admin/'
    | '/r/$slug/kategori/$cat'
    | '/r/$slug/kategori/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bantuan'
    | '/explore'
    | '/messages'
    | '/notifikasi'
    | '/privasi'
    | '/reset-password'
    | '/saved'
    | '/scan'
    | '/settings'
    | '/sitemap.xml'
    | '/tentang'
    | '/q/$code'
    | '/r/$slug'
    | '/admin/analytics'
    | '/admin/iklan'
    | '/admin/info'
    | '/admin/qr'
    | '/admin/region'
    | '/r/$slug/$loc'
    | '/r/$slug/jelajah'
    | '/r/$slug/messages'
    | '/r/$slug/scan'
    | '/r/$slug/settings'
    | '/admin'
    | '/r/$slug/kategori/$cat'
    | '/r/$slug/kategori'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bantuan'
    | '/explore'
    | '/messages'
    | '/notifikasi'
    | '/privasi'
    | '/reset-password'
    | '/saved'
    | '/scan'
    | '/settings'
    | '/sitemap.xml'
    | '/tentang'
    | '/_authenticated/admin'
    | '/q/$code'
    | '/r/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/iklan'
    | '/_authenticated/admin/info'
    | '/_authenticated/admin/qr'
    | '/_authenticated/admin/region'
    | '/r/$slug_/$loc'
    | '/r/$slug_/jelajah'
    | '/r/$slug_/messages'
    | '/r/$slug_/scan'
    | '/r/$slug_/settings'
    | '/_authenticated/admin/'
    | '/r/$slug_/kategori/$cat'
    | '/r/$slug_/kategori/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BantuanRoute: typeof BantuanRoute
  ExploreRoute: typeof ExploreRoute
  MessagesRoute: typeof MessagesRoute
  NotifikasiRoute: typeof NotifikasiRoute
  PrivasiRoute: typeof PrivasiRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
  QCodeRoute: typeof QCodeRoute
  RSlugRoute: typeof RSlugRoute
  RSlugLocRoute: typeof RSlugLocRoute
  RSlugJelajahRoute: typeof RSlugJelajahRoute
  RSlugMessagesRoute: typeof RSlugMessagesRoute
  RSlugScanRoute: typeof RSlugScanRoute
  RSlugSettingsRoute: typeof RSlugSettingsRoute
  RSlugKategoriCatRoute: typeof RSlugKategoriCatRoute
  RSlugKategoriIndexRoute: typeof RSlugKategoriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantuan': {
      id: '/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof BantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privasi': {
      id: '/privasi'
      path: '/privasi'
      fullPath: '/privasi'
      preLoaderRoute: typeof PrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/iklan': {
      id: '/_authenticated/admin/iklan'
      path: '/iklan'
      fullPath: '/admin/iklan'
      preLoaderRoute: typeof AuthenticatedAdminIklanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/info': {
      id: '/_authenticated/admin/info'
      path: '/info'
      fullPath: '/admin/info'
      preLoaderRoute: typeof AuthenticatedAdminInfoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qr': {
      id: '/_authenticated/admin/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AuthenticatedAdminQrRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/region': {
      id: '/_authenticated/admin/region'
      path: '/region'
      fullPath: '/admin/region'
      preLoaderRoute: typeof AuthenticatedAdminRegionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/r/$slug_/$loc': {
      id: '/r/$slug_/$loc'
      path: '/r/$slug/$loc'
      fullPath: '/r/$slug/$loc'
      preLoaderRoute: typeof RSlugLocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/jelajah': {
      id: '/r/$slug_/jelajah'
      path: '/r/$slug/jelajah'
      fullPath: '/r/$slug/jelajah'
      preLoaderRoute: typeof RSlugJelajahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/messages': {
      id: '/r/$slug_/messages'
      path: '/r/$slug/messages'
      fullPath: '/r/$slug/messages'
      preLoaderRoute: typeof RSlugMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/scan': {
      id: '/r/$slug_/scan'
      path: '/r/$slug/scan'
      fullPath: '/r/$slug/scan'
      preLoaderRoute: typeof RSlugScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/settings': {
      id: '/r/$slug_/settings'
      path: '/r/$slug/settings'
      fullPath: '/r/$slug/settings'
      preLoaderRoute: typeof RSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/kategori/': {
      id: '/r/$slug_/kategori/'
      path: '/r/$slug/kategori'
      fullPath: '/r/$slug/kategori/'
      preLoaderRoute: typeof RSlugKategoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/kategori/$cat': {
      id: '/r/$slug_/kategori/$cat'
      path: '/r/$slug/kategori/$cat'
      fullPath: '/r/$slug/kategori/$cat'
      preLoaderRoute: typeof RSlugKategoriCatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminIklanRoute: typeof AuthenticatedAdminIklanRoute
  AuthenticatedAdminInfoRoute: typeof AuthenticatedAdminInfoRoute
  AuthenticatedAdminQrRoute: typeof AuthenticatedAdminQrRoute
  AuthenticatedAdminRegionRoute: typeof AuthenticatedAdminRegionRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminIklanRoute: AuthenticatedAdminIklanRoute,
  AuthenticatedAdminInfoRoute: AuthenticatedAdminInfoRoute,
  AuthenticatedAdminQrRoute: AuthenticatedAdminQrRoute,
  AuthenticatedAdminRegionRoute: AuthenticatedAdminRegionRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BantuanRoute: BantuanRoute,
  ExploreRoute: ExploreRoute,
  MessagesRoute: MessagesRoute,
  NotifikasiRoute: NotifikasiRoute,
  PrivasiRoute: PrivasiRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
  QCodeRoute: QCodeRoute,
  RSlugRoute: RSlugRoute,
  RSlugLocRoute: RSlugLocRoute,
  RSlugJelajahRoute: RSlugJelajahRoute,
  RSlugMessagesRoute: RSlugMessagesRoute,
  RSlugScanRoute: RSlugScanRoute,
  RSlugSettingsRoute: RSlugSettingsRoute,
  RSlugKategoriCatRoute: RSlugKategoriCatRoute,
  RSlugKategoriIndexRoute: RSlugKategoriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
